### ISSUE TITLE
ModuleNotFoundError: No module named 'pyfiglet'

### ISSUE THREAD

**Issue by wankenobi666** [ngeteng/Shopee-flash-sale-shopee-github#8]
GImana cara selesaikan ini. gak bisa run shopee.py keluar error

File "C:\Shopee-flash-sale-shopee-github-main\shopee.py", line 2, in <module>
    import pyfiglet as f
ModuleNotFoundError: No module named 'pyfiglet'

**Comment by ahmadnurokhim** [comment]
Pasang dulu modul pyfigletnya atau bisa pake command
`pip3 install -r requirements.txt`

**Comment by bangkitboss** [comment]
Hallo @wankenobi666 ,  coba jalankan perintah

> pip3 install pyfiglet

atau bisa jalankan

> pip3 install -r requiremenst.txt

untuk lebih jelas bisa baca setingan dan pengaturannya [disini](https://www.sans.eu.org/2021/01/review-cara-kerja-bot-shopee-sans.html?m=1)
